### ISSUE TITLE
Issue with BottomSheet background.

### ISSUE THREAD

**Issue by fsdramjan** [md-siam/widget_of_the_day#1]
When I am pass the customPaint stack widget in bottomsheet then show me a white scaffold, When I am Wrap stack with Container/Sizebox then work perfectly, but In bottomsheet I found a layer ....Now I want the background transparent , How can I achive it?

![image](https://user-images.githubusercontent.com/83186779/164957429-3a566495-9400-4090-a6d9-0a05507e79fb.png)

**Comment by md-siam** [comment]
Do you mean this background ??

![Screen Shot 2022-04-24 at 6 14 45 PM](https://user-images.githubusercontent.com/21225918/164976032-4102359f-f7aa-4f16-8205-147b0eaa6fef.png)

**Comment by fsdramjan** [comment]
Yes brother,
How can I solve this issue?

**Comment by md-siam** [comment]
Use Stack()

**Comment by fsdramjan** [comment]
using stack.....


import 'package:flutter/material.dart';
import 'package:ionicons/ionicons.dart';
import 'package:needbox_customer/src/components/drawer/sidebarComponent.dart';
import 'package:needbox_customer/src/configs/appColors.dart';
import 'package:needbox_customer/src/pages/cart/cartPage.dart';
import 'package:needbox_customer/src/pages/home/homePage.dart';
import 'package:needbox_customer/src/pages/userAccount/profilePage.dart';
import 'package:needbox_customer/src/widgets/snackBar/customSnackbarWidget.dart';
import 'package:needbox_customer/src/widgets/textWidget/kText.dart';

class CustomBottomAppBar extends StatefulWidget {
  @override
  _CustomBottomAppBarState createState() => _CustomBottomAppBarState();
}

class _CustomBottomAppBarState extends State<CustomBottomAppBar> {
  int currentTab = 0;
  final PageStorageBucket bucket = PageStorageBucket();
  Widget _currentScreens = HomePage();

  var scaffoldKey = GlobalKey<ScaffoldState>();

  @override
  Widget build(BuildContext context) {
    final Size size = MediaQuery.of(context).size;
    return Scaffold(
      key: scaffoldKey,
      endDrawer: SidebarComponent(),
      body: PageStorage(
        bucket: bucket,
        child: _currentScreens,
      ),
      bottomSheet: SizedBox(
        height: 65,
        child: Stack(
          clipBehavior: Clip.none,
          children: [
            Positioned(
              bottom: 0,
              left: 0,
              child: Container(
                width: size.width,
                height: 70,
                child: Stack(
                  clipBehavior: Clip.none,
                  // overflow: Overflow.visible,
                  children: [
                    CustomPaint(
                      size: Size(size.width, 80),
                      painter: BNBCustomPainter(),
                    ),
                    Center(
                      heightFactor: 0.6,
                      child: Stack(
                        children: [
                          FloatingActionButton(
                            backgroundColor: orangeO50,
                            child: Icon(
                              Icons.shopping_basket,
                              color: white,
                            ),
                            elevation: 0.1,
                            onPressed: () {
                              setState(() {
                                _currentScreens = CartPage(
                                  isBackEnable: false,
                                );
                                currentTab = 5;
                              });
                            },
                          ),
                          Positioned(
                            right: 8,
                            top: 10,
                            child: CircleAvatar(
                              backgroundColor: white,
                              radius: 7,
                              child: KText(
                                text: '2',
                                fontSize: 11,
                                color: orangeO50,
                                fontWeight: FontWeight.bold,
                              ),
                            ),
                          ),
                        ],
                      ),
                    ),
                    Container(
                      width: size.width,
                      height: 80,
                      child: Row(
                        mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                        children: [
                          IconButton(
                            icon: Icon(
                              Icons.home,
                              color:
                                  currentTab == 0 ? orangeO50 : grey.shade400,
                            ),
                            onPressed: () {
                              setState(() {
                                _currentScreens = HomePage();
                                currentTab = 0;
                              });
                            },
                            splashColor: Colors.white,
                          ),
                          IconButton(
                              icon: Icon(
                                Ionicons.heart,
                                color:
                                    currentTab == 1 ? orangeO50 : grey.shade400,
                              ),
                              onPressed: () {
                                setState(() {
                                  snackBarWidget(
                                    title: 'Cooming soon!',
                                    message: 'This feature added soon.',
                                    isRed: false,
                                  );
                                  currentTab = 1;
                                });
                              }),
                          Container(
                            width: size.width * 0.20,
                          ),
                          IconButton(
                              icon: Icon(
                                Ionicons.person,
                                color:
                                    currentTab == 2 ? orangeO50 : grey.shade400,
                              ),
                              onPressed: () {
                                setState(() {
                                  _currentScreens = ProfilePage();
                                  currentTab = 2;
                                });
                              }),
                          IconButton(
                              icon: Icon(
                                Ionicons.menu,
                                color:
                                    currentTab == 3 ? orangeO50 : grey.shade400,
                              ),
                              onPressed: () {
                                scaffoldKey.currentState!.openEndDrawer();
                              }),
                        ],
                      ),
                    )
                  ],
                ),
              ),
            )
          ],
        ),
      ),
    );
  }
}

class BNBCustomPainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    Paint paint = Paint()
      ..color = white
      ..style = PaintingStyle.fill;

    Path path = Path();
    path.moveTo(0, 20); // Start
    path.quadraticBezierTo(size.width * 0.20, 0, size.width * 0.35, 0);
    path.quadraticBezierTo(size.width * 0.40, 0, size.width * 0.40, 20);
    path.arcToPoint(Offset(size.width * 0.60, 20),
        radius: Radius.circular(20.0), clockwise: false);
    path.quadraticBezierTo(size.width * 0.60, 0, size.width * 0.65, 0);
    path.quadraticBezierTo(size.width * 0.80, 0, size.width, 20);
    path.lineTo(size.width, size.height);
    path.lineTo(0, size.height);
    path.lineTo(0, 20);
    canvas.drawShadow(path, Colors.black, 5, true);
    canvas.drawPath(path, paint);
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) {
    return false;
  }
}

**Comment by md-siam** [comment]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/21225918/165281788-f0b21217-c859-4a5e-8bfc-5a9eefe0c293.gif)

**Comment by fsdramjan** [comment]
bro can you share your code?

**Comment by md-siam** [comment]
[home_page.md](https://github.com/md-siam/widget_of_the_day/files/8562558/home_page.md)

**Comment by md-siam** [comment]
Rename the file to "home_page.dart"

**Comment by fsdramjan** [comment]
issue solved...

**Comment by md-siam** [comment]
Bye. 
Happy coding 🙂
